// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbhvvsriyctjpcvibutp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiaHZ2c3JpeWN0anBjdmlidXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDE3OTgsImV4cCI6MjA2NDQxNzc5OH0.UIZnzHaYMH6d1pdKVLvDYwt_uFUOlbUXZXR0QRFYWq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);